networks:
  ktor-network:
    driver: bridge

services:
  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - /tmp/postgresql:/var/lib/postgresql
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - ktor-network
    environment:
      - POSTGRES_DB="ktor"
      - POSTGRES_HOST_AUTH_METHOD=trust
      - DEBUG=false
      - POSTGRES_USER=sample
      - POSTGRES_PASSWORD=sample
      - POSTGRES_DB=s-backend
  api:
    build: .
    container_name: api
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      - postgres
    networks:
      - ktor-network
    environment:
      - DB_TYPE=postgres
