CREATE TABLE "Sentences" (
  "text" varchar PRIMARY KEY NOT NULL,
  "timestamp" INTEGER NOT NULL,
  "sourceLanguage" varchar,
  "videoUriString" varchar,
  "timeStartSeconds" INTEGER,
  "timeEndSeconds" INTEGER,
  "audioUriString" varchar,
  "canExtractAudio" INTEGER NOT NULL DEFAULT 1,
  "translation" varchar
);

CREATE TABLE "Words" (
  "text" varchar PRIMARY KEY NOT NULL,
  "timestamp" INTEGER NOT NULL,
  "sourceLanguage" varchar,
  "translation" varchar,
  "repeated" INTEGER NOT NULL,
  "repeatedTotalTimes" INTEGER NOT NULL,
  "timeToRepeat" INTEGER NOT NULL,
  "repeatStage" INTEGER NOT NULL,
  "videoId" varchar
);

CREATE TABLE "SearchHistory" (
  "query" SERIAL PRIMARY KEY NOT NULL,
  "timestamp" INTEGER NOT NULL
);

CREATE TABLE "YouTubeVideo" (
  "id" varchar PRIMARY KEY NOT NULL,
  "title" varchar NOT NULL,
  "description" varchar,
  "channelTitle" varchar NOT NULL,
  "subsUriString" varchar,
  "previewUrl" varchar NOT NULL,
  "channelId" varchar,
  "sourceLang" varchar NOT NULL,
  "durationMs" INTEGER NOT NULL,
  "openedAtTs" INTEGER NOT NULL,
  "publishedAtTs" INTEGER NOT NULL,
  "difficulty" INTEGER,
  "autogeneratedSubtitles" boolean,
  "banned" boolean DEFAULT false,
  "reportedTimes" INTEGER DEFAULT 0,
  "requiresModeration" boolean DEFAULT true
);

CREATE TABLE "VideoMeta" (
  "videoId" varchar PRIMARY KEY,
  "searchTokens" TSVECTOR
);

CREATE TABLE "Subtitles" (
  "videoId" varchar PRIMARY KEY,
  "subtitles" varchar
);

CREATE TABLE "Topics" (
  "name" varchar PRIMARY KEY NOT NULL
);

CREATE TABLE "VideoTopic" (
  "id" INTEGER PRIMARY KEY NOT NULL,
  "videoId" varchar NOT NULL,
  "topicId" varchar NOT NULL
);

CREATE TABLE "TopicTranslation" (
  "id" INTEGER PRIMARY KEY NOT NULL,
  "topicId" varchar,
  "language" varchar,
  "name" varchar
);

CREATE TABLE "UserSettings" (
  "userId" varchar PRIMARY KEY NOT NULL,
  "lanOrig" INTEGER,
  "lanTran" INTEGER
);

CREATE TABLE "UserTopics" (
  "id" int PRIMARY KEY NOT NULL,
  "userId" varchar,
  "topicId" varchar
);

CREATE TABLE "User" (
  "id" varchar PRIMARY KEY,
  "name" varchar,
  "registerTs" INTEGER
);

CREATE TABLE "UserWatchHistory" (
  "id" INTEGER PRIMARY KEY,
  "userId" varchar,
  "videoId" varchar,
  "watchedTs" INTEGER,
  "seekPositionPercent" INTEGER,
  "saved" boolean
);

CREATE TABLE "RecommendLess" (
  "id" INTEGER PRIMARY KEY,
  "userId" varchar,
  "videoId" varchar
);

CREATE TABLE "Language" (
  "id" INTEGER PRIMARY KEY,
  "displayName" varchar,
  "inSources" boolean,
  "inTranslates" boolean
);

CREATE TABLE "Playlist" (
  "id" varchar PRIMARY KEY NOT NULL,
  "imageUrl" varchar NOT NULL,
  "videosCount" INTEGER NOT NULL,
  "title" varchar NOT NULL,
  "subtitle" varchar NOT NULL,
  "language" varchar NOT NULL,
  "timestamp" INTEGER NOT NULL
);

CREATE TABLE "PlaylistVideo" (
  "playlistId" varchar PRIMARY KEY,
  "videoId" varchar
);

CREATE TABLE "WordUsages" (
  "word" varchar PRIMARY KEY NOT NULL,
  "sentence" varchar NOT NULL
);

CREATE TABLE "DailyWordsLearned" (
  "date" varchar PRIMARY KEY NOT NULL,
  "wordsCount" INTEGER NOT NULL
);

COMMENT ON TABLE "YouTubeVideo" IS 'YouTube videos';

COMMENT ON COLUMN "VideoMeta"."searchTokens" IS 'Search tokens retrieved from title + description + subtitles';

COMMENT ON COLUMN "Topics"."name" IS 'English name';

COMMENT ON COLUMN "User"."registerTs" IS 'Registration Timestamp. To calculate how long this user with us';

COMMENT ON COLUMN "UserWatchHistory"."seekPositionPercent" IS '[1;100]';

ALTER TABLE "UserTopics" ADD FOREIGN KEY ("userId") REFERENCES "User" ("id");

ALTER TABLE "UserTopics" ADD FOREIGN KEY ("topicId") REFERENCES "Topics" ("name");

ALTER TABLE "RecommendLess" ADD FOREIGN KEY ("userId") REFERENCES "User" ("id");

ALTER TABLE "RecommendLess" ADD FOREIGN KEY ("videoId") REFERENCES "YouTubeVideo" ("id");

ALTER TABLE "VideoMeta" ADD FOREIGN KEY ("videoId") REFERENCES "YouTubeVideo" ("id");

ALTER TABLE "Subtitles" ADD FOREIGN KEY ("videoId") REFERENCES "YouTubeVideo" ("id");

ALTER TABLE "VideoTopic" ADD FOREIGN KEY ("topicId") REFERENCES "Topics" ("name") ON DELETE CASCADE ON UPDATE NO ACTION;

ALTER TABLE "VideoTopic" ADD FOREIGN KEY ("videoId") REFERENCES "YouTubeVideo" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;

ALTER TABLE "UserSettings" ADD FOREIGN KEY ("lanTran") REFERENCES "Language" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;

ALTER TABLE "UserSettings" ADD FOREIGN KEY ("lanOrig") REFERENCES "Language" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;

ALTER TABLE "User" ADD FOREIGN KEY ("id") REFERENCES "UserSettings" ("userId") ON DELETE CASCADE ON UPDATE NO ACTION;

ALTER TABLE "TopicTranslation" ADD FOREIGN KEY ("topicId") REFERENCES "Topics" ("name") ON DELETE CASCADE ON UPDATE NO ACTION;

ALTER TABLE "PlaylistVideo" ADD FOREIGN KEY ("playlistId") REFERENCES "Playlist" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;

ALTER TABLE "PlaylistVideo" ADD FOREIGN KEY ("videoId") REFERENCES "YouTubeVideo" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;

ALTER TABLE "UserWatchHistory" ADD FOREIGN KEY ("videoId") REFERENCES "YouTubeVideo" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;

ALTER TABLE "UserWatchHistory" ADD FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;

ALTER TABLE "WordUsages" ADD FOREIGN KEY ("word") REFERENCES "Words" ("text") ON DELETE CASCADE ON UPDATE NO ACTION;
