package ru.vorobeij.backend.sub.routing.db.utils.schema

import java.util.UUID
import org.jetbrains.exposed.sql.insert
import ru.vorobeij.backend.sub.database.tables.YouTubeVideos

@Suppress("TOO_MANY_PARAMETERS", "TOO_MANY_LINES_IN_LAMBDA")
fun YouTubeVideos.insert(
    id: String = UUID.randomUUID().toString().take(10),
    title: String = UUID.randomUUID().toString().take(10),
    description: String = UUID.randomUUID().toString().take(10),
    channelTitle: String = UUID.randomUUID().toString().take(10),
    subsUriString: String = UUID.randomUUID().toString().take(10),
    previewUrl: String = UUID.randomUUID().toString().take(10),
    channelId: String = UUID.randomUUID().toString().take(10),
    sourceLang: String = UUID.randomUUID().toString().take(10),
    durationMs: Long = 0,
    openedAtTs: Long = 0,
    publishedAtTs: Long = 0,
    difficulty: Int = 0,
    autogeneratedSubtitles: Boolean = true,
    banned: Boolean = false,
    requiresModeration: Boolean = true,
    language: String = "en"
) = insert {
    it[YouTubeVideos.id] = id
    it[YouTubeVideos.title] = title
    it[YouTubeVideos.description] = description
    it[YouTubeVideos.channelTitle] = channelTitle
    it[YouTubeVideos.subsUriString] = subsUriString
    it[YouTubeVideos.previewUrl] = previewUrl
    it[YouTubeVideos.channelId] = channelId
    it[YouTubeVideos.sourceLang] = sourceLang
    it[YouTubeVideos.durationMs] = durationMs
    it[YouTubeVideos.openedAtTs] = openedAtTs
    it[YouTubeVideos.publishedAtTs] = publishedAtTs
    it[YouTubeVideos.difficulty] = difficulty
    it[YouTubeVideos.autogeneratedSubtitles] = autogeneratedSubtitles
    it[YouTubeVideos.banned] = banned
    it[YouTubeVideos.requiresModeration] = requiresModeration
    it[YouTubeVideos.language] = language
}
